export type Locale = 'en' | 'zh-CN';

export const copy = {
    en: {
        appTitle: 'Fresnica',
        home: 'Home',
        activity: 'Activity',
        scan: 'Scan',
        explore: 'Explore',
        settings: 'Settings',
        mainWallet: 'Main wallet',
        address: 'GABC1234...WXYZ5678',
        network: 'Network',
        online: 'Online',
        offline: 'Offline',
        assets: 'Assets',
        send: 'Send',
        swap: 'Swap',
        receive: 'Receive',
        comingSoon: 'Swap and Receive will be enabled after their product flows are specified.',
        xlmBalance: '12,480.50 XLM',
        usdcBalance: '2,350.00 USDC',
        noActivity: 'No activity yet',
        noActivityDescription: 'Completed wallet activity will appear here.',
        scanTitle: 'Scan',
        scanDescription: 'Camera access is requested only when you choose to scan.',
        cameraAction: 'Allow camera',
        cameraGranted: 'Camera permission granted',
        cameraDenied: 'Camera permission not granted',
        exploreTitle: 'Explore',
        exploreDescription: 'Network-aware discovery will live here. The shell currently reports connection state only.',
        settingsTitle: 'Settings',
        themeGroup: 'Theme',
        languageGroup: 'Language',
        system: 'System',
        light: 'Light',
        dark: 'Dark',
        english: 'English',
        chinese: '简体中文',
        reducedMotionOn: 'Reduced motion is enabled',
        reducedMotionOff: 'Reduced motion is not enabled',
        transferTitle: 'Send',
        back: 'Back',
        recipient: 'Recipient',
        recipientPlaceholder: 'Enter address',
        amount: 'Amount',
        amountPlaceholder: 'Enter amount',
        review: 'Review transfer',
        transferHint: 'This slice validates the product shell only. It does not sign or submit transactions.',
    },
    'zh-CN': {
        appTitle: 'Fresnica',
        home: '首页',
        activity: '活动',
        scan: '扫码',
        explore: '探索',
        settings: '设置',
        mainWallet: '主钱包',
        address: 'GABC1234...WXYZ5678',
        network: '网络',
        online: '在线',
        offline: '离线',
        assets: '资产',
        send: '发送',
        swap: '兑换',
        receive: '接收',
        comingSoon: '兑换和接收将在对应产品流程确定后启用。',
        xlmBalance: '12,480.50 XLM',
        usdcBalance: '2,350.00 USDC',
        noActivity: '暂无活动',
        noActivityDescription: '完成的钱包活动会显示在这里。',
        scanTitle: '扫码',
        scanDescription: '只有在你主动选择扫码时才会请求相机权限。',
        cameraAction: '允许相机',
        cameraGranted: '已获得相机权限',
        cameraDenied: '尚未获得相机权限',
        exploreTitle: '探索',
        exploreDescription: '后续会在这里接入联网发现能力；当前壳层只展示连接状态。',
        settingsTitle: '设置',
        themeGroup: '主题',
        languageGroup: '语言',
        system: '跟随系统',
        light: '浅色',
        dark: '深色',
        english: 'English',
        chinese: '简体中文',
        reducedMotionOn: '已启用减少动态效果',
        reducedMotionOff: '未启用减少动态效果',
        transferTitle: '发送',
        back: '返回',
        recipient: '收款地址',
        recipientPlaceholder: '输入地址',
        amount: '金额',
        amountPlaceholder: '输入金额',
        review: '检查转账',
        transferHint: '当前切片只验证产品壳层，不会签名或提交交易。',
    },
} as const;

export type ProductCopy = (typeof copy)['en'];
